destination: ./_site
lsi:         false
port:        4000
markdown:    kramdown
permalink:   none
pygments:    true
pagination:  false
exclude:     [foundation]
name:        site name
description: site description
url:         http://example.com
baseurl:     ''
liveFyreId:  ''
ga:          ''
